language: go

dist: xenial

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

matrix:
  include:
    - go: "1.11.x"
    - go: "1.12.x"
    - go: tip
  allow_failures:
    - go: tip

install:
  - go vet ./...
  - gofmt -s -l .

script:
  - go build ./cmd/ginvalid
